global:
  smtp_from: "{{ _secrets.mail.address }}"
  smtp_smarthost: "mail.infomaniak.com:587"
  smtp_auth_username: "{{ _secrets.mail.username }}"
  smtp_auth_password: "{{ _secrets.mail.password }}"
  smtp_require_tls: true

templates:
  - "/etc/alertmanager/template/*.tmpl"

receivers:
  - name: "email"
    email_configs:
      - to: "{{ _secrets.alertmanager.emails | join(', ') }}"

  - name: "telegram"
    telegram_configs:
      - api_url: https://api.telegram.org
        bot_token: "{{ _secrets.alertmanager.telegram.token }}"
        chat_id: {{ _secrets.alertmanager.telegram.chat }}

route:
  group_by: [instance]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: "telegram"

  routes:
    - matchers:
        - severity = critical
      continue: true
      receiver: "email"
    
    - matchers:
        - severity = critical
      receiver: "telegram"

