- include_vars: ../../vars/main.yml

- name: Run node_exporter
  docker_container:
      name: '{{ nodeexporter_container_name }}'
      image: '{{ nodeexporter_image }}:{{ nodeexporter_version }}'
      detach: yes
      restart_policy: unless-stopped
      pid_mode: host
      command:
          - '--path.rootfs=/host'
      network_mode: default
      networks:
          - name: '{{ monitoring_network_name }}'
      volumes:
          - /:/host:ro,rslave
      log_driver: json-file
      log_options:
          max-size: 50m
          max-file: '3'
      labels:
          traefik.enable: 'fasle'
          traefik.http.routers.nodeexporter.rule: 'Host(`nodeexporter.{{ frontend.domain }}`)'
          traefik.http.routers.nodeexporter.entrypoints: 'websecure'
          traefik.http.routers.nodeexporter.tls.certresolver: 'letsencrypt'
          traefik.docker.network: '{{ backend_network_name }}'
