alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: traefik
    scrape_interval: 30s
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: grafana
    scrape_interval: 30s
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: blackbox
    metrics_path: /metrics
    static_configs:
      - targets:
          - blackbox-exporter:9115

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: [http_code]
    static_configs:
      - targets:
          - https://kooked.ch
          - https://duriaux.ch
          - https://calendar.kooked.ch
          - https://musics.kooked.ch
          - https://grafana.kooked.ch
          - https://traefik.kooked.ch
          - https://moodle.kooked.ch
          - https://nodered.kooked.ch
          - https://pictures.kooked.ch
          - https://prometheus.kooked.ch
          - https://am.kooked.ch
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
